name: Deploy Azure Backend Resources

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ARM Template as Deployment Stack
        run: |
          OPENAPI_CONTENT=$(base64 -w 0 openapi.yaml)
          az stack group validate \
            --name chatapp-backend-stack \
            --resource-group chatapp-rg \
            --template-file ./infra/azure-backend-resources.json \
            --deny-settings-mode None \
            --action-on-unmanage deleteResources \
            --parameters @infra/azure-backend-parameters.json \
                         openApiSpecContent="$OPENAPI_CONTENT"
