name: Build Chat App

on:
  push:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 2: Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # Or 'zulu', 'corretto', etc.
          java-version: "21"

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean package
        working-directory: chatAppBackend

      # Step 4: Copy the JAR (assuming one main JAR)
      - name: Copy JAR to a separate folder
        run: |
          mkdir -p output
          cp chatAppBackend/target/*.jar output/

      # Step 5: Upload artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: chat-app-jar
          path: output/*.jar

      - name: Get ACR credentials from Key Vault
        run: |
          ACR_USERNAME=$(az keyvault secret show --vault-name "chatapp-kv-123" --name "acr-username" --query value -o tsv)
          ACR_PASSWORD=$(az keyvault secret show --vault-name "chatapp-kv-123" --name "acr-password" --query value -o tsv)
          echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV

      - name: Build & push image
        run: |

          # Docker login to ACR
          echo $ACR_PASSWORD | docker login chatappacrazurebackend.azurecr.io --username $ACR_USERNAME --password-stdin

          # Build Docker image with commit SHA and latest tags
          docker build -t chatappacrazurebackend.azurecr.io/chatappbackend:${{ github.sha }} \
                      -t chatappacrazurebackend.azurecr.io/chatappbackend:latest build/

          # Push both tags
          docker push chatappacrazurebackend.azurecr.io/chatappbackend:${{ github.sha }}
          docker push chatappacrazurebackend.azurecr.io/chatappbackend:latest
