name: Build Chat App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # Or 'zulu', 'corretto', etc.
          java-version: "21"

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean package
        working-directory: chatAppBackend

      # Step 4: Copy the JAR (assuming one main JAR)
      - name: Copy JAR to a separate folder
        run: |
          mkdir -p output
          cp chatAppBackend/target/*.jar output/

      # Step 5: Upload artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: chat-app-jar
          path: output/*.jar
